FROM aichallenge-2025-dev:latest

USER root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        gnupg \
        software-properties-common \
    && add-apt-repository -y ppa:kisak/turtle \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        libegl-mesa0 libgbm1 libgl1-mesa-dri libglx-mesa0 libvulkan1 \
        mesa-vulkan-drivers vulkan-tools \
    && rm -rf /var/lib/apt/lists/*
